In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder

In [3]:
df=pd.read_csv("Promotions.csv")
df

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,73,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54803,3030,Technology,region_14,Bachelor's,m,sourcing,1,48,3.0,17,0,78,0
54804,74592,Operations,region_27,Master's & above,f,other,1,37,2.0,6,0,56,0
54805,13918,Analytics,region_1,Bachelor's,m,other,1,27,5.0,3,0,79,0
54806,13614,Sales & Marketing,region_9,NaN,m,sourcing,1,29,1.0,2,0,45,0
54807,51526,HR,region_22,Bachelor's,m,other,1,27,1.0,5,0,49,0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_id           54808 non-null  int64
 1   department            54808 non-null  object
 2   region                54808 non-null  object
 3   education             52399 non-null  object
 4   gender                54808 non-null  object
 5   recruitment_channel   54808 non-null  object
 6   no_of_trainings       54808 non-null  int64
 7   age                   54808 non-null  int64
 8   previous_year_rating  50684 non-null  float64
 9   length_of_service     54808 non-null  int64
 10  awards_won?           54808 non-null  int64
 11  avg_training_score    54808 non-null  int64
 12  is_promoted           54808 non-null  int64
dtypes: float64(1), int64(7), object(5)
memory usage: 5.4+ MB

In [5]:
df.head(10)

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,73,0
5,58896,Analytics,region_2,Bachelor's,m,sourcing,2,31,3.0,7,0,85,0
6,20379,Operations,region_20,Bachelor's,f,other,1,31,3.0,5,0,59,0
7,16290,Operations,region_34,Master's & above,m,sourcing,1,33,3.0,6,0,63,0
8,73202,Analytics,region_20,Bachelor's,m,other,1,28,4.0,5,0,83,0
9,28911,Sales & Marketing,region_1,Master's & above,m,sourcing,1,32,5.0,5,0,54,0

In [7]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,54798,54799,54800,54801,54802,54803,54804,54805,54806,54807
employee_id,65438,65141,7513,2542,48945,58896,20379,16290,73202,28911,...,40257,68093,39227,12431,6915,3030,74592,13918,13614,51526
department,Sales & Marketing,Operations,Sales & Marketing,Sales & Marketing,Technology,Analytics,Operations,Operations,Analytics,Sales & Marketing,...,Sales & Marketing,Procurement,HR,Technology,Sales & Marketing,Technology,Operations,Analytics,Sales & Marketing,HR
region,region_7,region_22,region_19,region_23,region_26,region_2,region_20,region_34,region_20,region_1,...,region_2,region_2,region_11,region_26,region_14,region_14,region_27,region_1,region_9,region_22
education,Master's & above,Bachelor's,Bachelor's,Bachelor's,Bachelor's,Bachelor's,Bachelor's,Master's & above,Bachelor's,Master's & above,...,Master's & above,Master's & above,Bachelor's,Bachelor's,Bachelor's,Bachelor's,Master's & above,Bachelor's,NaN,Bachelor's
gender,f,m,m,m,m,m,f,m,m,m,...,f,f,m,f,m,m,f,m,m,m
recruitment_channel,sourcing,other,sourcing,other,other,sourcing,other,sourcing,other,sourcing,...,other,other,other,sourcing,other,sourcing,other,other,sourcing,other
no_of_trainings,1,1,1,2,1,2,1,1,1,1,...,2,1,2,1,2,1,1,1,1,1
age,35,30,34,39,45,31,31,33,28,32,...,40,50,34,31,31,48,37,27,29,27
previous_year_rating,5.0,5.0,3.0,1.0,3.0,3.0,3.0,3.0,4.0,5.0,...,5.0,5.0,5.0,NaN,1.0,3.0,2.0,5.0,1.0,1.0
length_of_service,8,4,7,10,2,7,5,6,5,5,...,4,6,3,1,2,17,6,3,2,5
awards_won?,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
avg_training_score,49,60,50,50,73,85,59,63,83,54,...,51,67,52,78,49,78,56,79,45,49
is_promoted,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
df.tail(10)

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won?,avg_training_score,is_promoted
54798,40257,Sales & Marketing,region_2,Master's & above,f,other,2,40,5.0,4,0,51,0
54799,68093,Procurement,region_2,Master's & above,f,other,1,50,5.0,6,1,67,0
54800,39227,HR,region_11,Bachelor's,m,other,2,34,5.0,3,0,52,0
54801,12431,Technology,region_26,Bachelor's,f,sourcing,1,31,NaN,1,0,78,0
54802,6915,Sales & Marketing,region_14,Bachelor's,m,other,2,31,1.0,2,0,49,0
54803,3030,Technology,region_14,Bachelor's,m,sourcing,1,48,3.0,17,0,78,0
54804,74592,Operations,region_27,Master's & above,f,other,1,37,2.0,6,0,56,0
54805,13918,Analytics,region_1,Bachelor's,m,other,1,27,5.0,3,0,79,0
54806,13614,Sales & Marketing,region_9,NaN,m,sourcing,1,29,1.0,2,0,45,0
54807,51526,HR,region_22,Bachelor's,m,other,1,27,1.0,5,0,49,0

In [10]:
df.select_dtypes(exclude="O").columns

Index(['employee_id', 'no_of_trainings', 'age', 'previous_year_rating',
       'length_of_service', 'awards_won?', 'avg_training_score',
       'is_promoted'],
      dtype='object')

In [11]:
df.isnull().sum()

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.describe()

,employee_id,no_of_trainings,age,previous_year_rating,length_of_service,awards_won?,avg_training_score,is_promoted
count,54808.000000,54808.000000,54808.000000,50684.000000,54808.000000,54808.000000,54808.000000,54808.000000
mean,39195.830627,1.253011,34.803915,3.329256,5.865512,0.023172,63.386750,0.085170
std,22586.581449,0.609264,7.660169,1.259993,4.265094,0.150450,13.371559,0.279137
min,1.000000,1.000000,20.000000,1.000000,1.000000,0.000000,39.000000,0.000000
25%,19669.750000,1.000000,29.000000,3.000000,3.000000,0.000000,51.000000,0.000000
50%,39225.500000,1.000000,33.000000,3.000000,5.000000,0.000000,60.000000,0.000000
75%,58730.500000,1.000000,39.000000,4.000000,7.000000,0.000000,76.000000,0.000000
max,78298.000000,10.000000,60.000000,5.000000,37.000000,1.000000,99.000000,1.000000

In [14]:
df.corr(numeric_only = True)

,employee_id,no_of_trainings,age,previous_year_rating,length_of_service,awards_won?,avg_training_score,is_promoted
employee_id,1.000000,-0.005121,0.000437,0.004533,0.001274,0.008420,-0.000586,0.001206
no_of_trainings,-0.005121,1.000000,-0.081278,-0.063126,-0.057275,-0.007628,0.042517,-0.024896
age,0.000437,-0.081278,1.000000,0.006008,0.657111,-0.008169,-0.048380,-0.017166
previous_year_rating,0.004533,-0.063126,0.006008,1.000000,0.000253,0.027738,0.075139,0.159320
length_of_service,0.001274,-0.057275,0.657111,0.000253,1.000000,-0.039927,-0.038122,-0.010670
awards_won?,0.008420,-0.007628,-0.008169,0.027738,-0.039927,1.000000,0.072138,0.195871
avg_training_score,-0.000586,0.042517,-0.048380,0.075139,-0.038122,0.072138,1.000000,0.181147
is_promoted,0.001206,-0.024896,-0.017166,0.159320,-0.010670,0.195871,0.181147,1.000000

In [21]:
Lb=LabelEncoder()
df['gender']=Lb.fit_transform(df['gender'])
df

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,0,sourcing,1,35,5.0,8,0,49,0
1,65141,Operations,region_22,Bachelor's,1,other,1,30,5.0,4,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,1,sourcing,1,34,3.0,7,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,1,other,2,39,1.0,10,0,50,0
4,48945,Technology,region_26,Bachelor's,1,other,1,45,3.0,2,0,73,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54803,3030,Technology,region_14,Bachelor's,1,sourcing,1,48,3.0,17,0,78,0
54804,74592,Operations,region_27,Master's & above,0,other,1,37,2.0,6,0,56,0
54805,13918,Analytics,region_1,Bachelor's,1,other,1,27,5.0,3,0,79,0
54806,13614,Sales & Marketing,region_9,NaN,1,sourcing,1,29,1.0,2,0,45,0
54807,51526,HR,region_22,Bachelor's,1,other,1,27,1.0,5,0,49,0

In [27]:
df['department'].unique()

array(['Sales & Marketing', 'Operations', 'Technology', 'Analytics',
       'R&D', 'Procurement', 'Finance', 'HR', 'Legal'], dtype=object)

In [23]:
data = df
data

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,0,sourcing,1,35,5.0,8,0,49,0
1,65141,Operations,region_22,Bachelor's,1,other,1,30,5.0,4,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,1,sourcing,1,34,3.0,7,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,1,other,2,39,1.0,10,0,50,0
4,48945,Technology,region_26,Bachelor's,1,other,1,45,3.0,2,0,73,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54803,3030,Technology,region_14,Bachelor's,1,sourcing,1,48,3.0,17,0,78,0
54804,74592,Operations,region_27,Master's & above,0,other,1,37,2.0,6,0,56,0
54805,13918,Analytics,region_1,Bachelor's,1,other,1,27,5.0,3,0,79,0
54806,13614,Sales & Marketing,region_9,NaN,1,sourcing,1,29,1.0,2,0,45,0
54807,51526,HR,region_22,Bachelor's,1,other,1,27,1.0,5,0,49,0

In [28]:
od=OrdinalEncoder(categories=[['Sales & Marketing', 'Operations', 'Technology', 'Analytics',
       'R&D', 'Procurement', 'Finance', 'HR', 'Legal']])
data['department']=od.fit_transform(data[['department']])
data

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won?,avg_training_score,is_promoted
0,65438,0.0,region_7,Master's & above,0,sourcing,1,35,5.0,8,0,49,0
1,65141,1.0,region_22,Bachelor's,1,other,1,30,5.0,4,0,60,0
2,7513,0.0,region_19,Bachelor's,1,sourcing,1,34,3.0,7,0,50,0
3,2542,0.0,region_23,Bachelor's,1,other,2,39,1.0,10,0,50,0
4,48945,2.0,region_26,Bachelor's,1,other,1,45,3.0,2,0,73,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54803,3030,2.0,region_14,Bachelor's,1,sourcing,1,48,3.0,17,0,78,0
54804,74592,1.0,region_27,Master's & above,0,other,1,37,2.0,6,0,56,0
54805,13918,3.0,region_1,Bachelor's,1,other,1,27,5.0,3,0,79,0
54806,13614,0.0,region_9,NaN,1,sourcing,1,29,1.0,2,0,45,0
54807,51526,7.0,region_22,Bachelor's,1,other,1,27,1.0,5,0,49,0

In [29]:
ohe=OneHotEncoder()
K=ohe.fit_transform(df[['department']])
j = K.toarray()
j

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], shape=(54808, 9))

In [18]:
df.head(5)

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,73,0