In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder

In [2]:
df=pd.read_csv("purchasetarget.csv")
df

   OrderId Country  Amout($)
0      102   India       300
1      314   Japan       200
2      290   India       100
3      897     Usa       890
4      187   India       200
5      980   Japan       100

In [3]:
data = df
data

   OrderId Country  Amout($)
0      102   India       300
1      314   Japan       200
2      290   India       100
3      897     Usa       890
4      187   India       200
5      980   Japan       100

In [4]:
Lb=LabelEncoder()
data['Country']=Lb.fit_transform(data['Country'])
data

   OrderId  Country  Amout($)
0      102        0       300
1      314        1       200
2      290        0       100
3      897        2       890
4      187        0       200
5      980        1       100