### Machine Learning = *Machine learning is a branch of Artificial Intelligence that focuses on developing models and algorithms that let computers learn from data without being explicitly programmed for every task. In simple words, ML teaches systems to think and understand like humans by learning from the data.*

THER ARE TWO TYPE OF DATA 
1. NUMERICAL
2. CATEGORICAL
    *

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder

In [2]:
df=pd.read_csv("PROPERTIES - PROPERTIES.csv")
df

         Area    Sqft   Price   Review
0    MP NAGAR  2600.0  550000     Poor
1    MP NAGAR     NaN  565000  Average
2    MP NAGAR  3200.0  610000     Good
3    MP NAGAR  3600.0  680000  Average
4    MP NAGAR  4000.0  725000  Average
5     NEW MKT  2600.0  585000     Good
6     NEW MKT  2800.0  615000     Good
7     NEW MKT  3300.0  650000     Good
8     NEW MKT  3600.0  710000     Good
9   INDRAPURI  2600.0  575000     Poor
10  INDRAPURI  2900.0  600000  Average
11  INDRAPURI  3100.0  620000  Average
12  INDRAPURI  3600.0  695000     Good

In [3]:
data = df
data

         Area    Sqft   Price   Review
0    MP NAGAR  2600.0  550000     Poor
1    MP NAGAR     NaN  565000  Average
2    MP NAGAR  3200.0  610000     Good
3    MP NAGAR  3600.0  680000  Average
4    MP NAGAR  4000.0  725000  Average
5     NEW MKT  2600.0  585000     Good
6     NEW MKT  2800.0  615000     Good
7     NEW MKT  3300.0  650000     Good
8     NEW MKT  3600.0  710000     Good
9   INDRAPURI  2600.0  575000     Poor
10  INDRAPURI  2900.0  600000  Average
11  INDRAPURI  3100.0  620000  Average
12  INDRAPURI  3600.0  695000     Good

In [9]:
Lb=LabelEncoder()
data['Area']=Lb.fit_transform(data['Area'])
data

    Area    Sqft   Price   Review
0      1  2600.0  550000     Poor
1      1     NaN  565000  Average
2      1  3200.0  610000     Good
3      1  3600.0  680000  Average
4      1  4000.0  725000  Average
5      2  2600.0  585000     Good
6      2  2800.0  615000     Good
7      2  3300.0  650000     Good
8      2  3600.0  710000     Good
9      0  2600.0  575000     Poor
10     0  2900.0  600000  Average
11     0  3100.0  620000  Average
12     0  3600.0  695000     Good

In [10]:
data['Review'].unique()

array(['Poor', 'Average', 'Good'], dtype=object)

In [11]:
od=OrdinalEncoder(categories=[['Poor', 'Average', 'Good']])
data['Review']=od.fit_transform(data[['Review']])
data

    Area    Sqft   Price  Review
0      1  2600.0  550000     0.0
1      1     NaN  565000     1.0
2      1  3200.0  610000     2.0
3      1  3600.0  680000     1.0
4      1  4000.0  725000     1.0
5      2  2600.0  585000     2.0
6      2  2800.0  615000     2.0
7      2  3300.0  650000     2.0
8      2  3600.0  710000     2.0
9      0  2600.0  575000     0.0
10     0  2900.0  600000     1.0
11     0  3100.0  620000     1.0
12     0  3600.0  695000     2.0

In [12]:
# Lb=LabelEncoder()
# data['Review']=Lb.fit_transform(data['Review'])
# data

using dic

In [15]:
dt = data
df

    Area    Sqft   Price  Review
0      1  2600.0  550000     0.0
1      1     NaN  565000     1.0
2      1  3200.0  610000     2.0
3      1  3600.0  680000     1.0
4      1  4000.0  725000     1.0
5      2  2600.0  585000     2.0
6      2  2800.0  615000     2.0
7      2  3300.0  650000     2.0
8      2  3600.0  710000     2.0
9      0  2600.0  575000     0.0
10     0  2900.0  600000     1.0
11     0  3100.0  620000     1.0
12     0  3600.0  695000     2.0

In [7]:
df["Review"].unique()
op= {'Poor':0, 'Average':1, 'Good':2}
op
df["Review"]=df["Review"].map(op)
df

         Area    Sqft   Price  Review
0    MP NAGAR  2600.0  550000       0
1    MP NAGAR     NaN  565000       1
2    MP NAGAR  3200.0  610000       2
3    MP NAGAR  3600.0  680000       1
4    MP NAGAR  4000.0  725000       1
5     NEW MKT  2600.0  585000       2
6     NEW MKT  2800.0  615000       2
7     NEW MKT  3300.0  650000       2
8     NEW MKT  3600.0  710000       2
9   INDRAPURI  2600.0  575000       0
10  INDRAPURI  2900.0  600000       1
11  INDRAPURI  3100.0  620000       1
12  INDRAPURI  3600.0  695000       2

Dummies only one hot me hota hai

In [4]:
df = pd.get_dummies(df,columns=['Area'], prefix="new", dtype = np.int32)
df

      Sqft   Price   Review  new_INDRAPURI  new_MP NAGAR  new_NEW MKT
0   2600.0  550000     Poor              0             1            0
1      NaN  565000  Average              0             1            0
2   3200.0  610000     Good              0             1            0
3   3600.0  680000  Average              0             1            0
4   4000.0  725000  Average              0             1            0
5   2600.0  585000     Good              0             0            1
6   2800.0  615000     Good              0             0            1
7   3300.0  650000     Good              0             0            1
8   3600.0  710000     Good              0             0            1
9   2600.0  575000     Poor              1             0            0
10  2900.0  600000  Average              1             0            0
11  3100.0  620000  Average              1             0            0
12  3600.0  695000     Good              1             0            0