In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder, TargetEncoder

In [24]:
df = pd.DataFrame(
    {
        'Country': ['India', 'USA', 'India', 'UK', 'USA', 'India', 'UK','USA'],
        'Purchased': [1,0,1,1,0,0,1,1]
    }
)

In [25]:
df

  Country  Purchased
0   India          1
1     USA          0
2   India          1
3      UK          1
4     USA          0
5   India          0
6      UK          1
7     USA          1

In [26]:
data = df
data

  Country  Purchased
0   India          1
1     USA          0
2   India          1
3      UK          1
4     USA          0
5   India          0
6      UK          1
7     USA          1

#### using pandas

In [27]:
k = data.groupby('Country')['Purchased'].mean()
print(k)

Country
India    0.666667
UK       1.000000
USA      0.333333
Name: Purchased, dtype: float64

In [28]:
data['Country'] = data['Country'].map(k)

In [29]:
data

    Country  Purchased
0  0.666667          1
1  0.333333          0
2  0.666667          1
3  1.000000          1
4  0.333333          0
5  0.666667          0
6  1.000000          1
7  0.333333          1

### using targetEncoder

In [30]:
Tr = TargetEncoder()

In [31]:
# Tr

In [32]:
l = Tr.fit(data[["Country"]],data["Purchased"])
l

TargetEncoder()

In [33]:
Tr.transform([[l]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but TargetEncoder was fitted with feature names
  warnings.warn(

array([[0.625]])

In [34]:
smooth=3

In [35]:
ff = pd.DataFrame(
    {
        'Country': ['India', 'USA', 'India', 'UK', 'USA', 'India', 'UK'],
        'Purchased': [1,0,1,1,0,0,1]
    }
)

In [36]:
ff

  Country  Purchased
0   India          1
1     USA          0
2   India          1
3      UK          1
4     USA          0
5   India          0
6      UK          1

In [37]:
Tr = TargetEncoder(smooth=3)

In [38]:
y = Tr.fit(ff[["Country"]],ff["Purchased"])
y

TargetEncoder(smooth=3)

In [39]:
Tr.transform([[y]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but TargetEncoder was fitted with feature names
  warnings.warn(

array([[0.57142857]])